//
// Copyright (c) 2018 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
= MicroProfile Config Sample

This sample shows how to use the MicroProfile Config API.

== Access the Application
The following REST APi is provided by the application. +

* **/list/all**: Lists all configurations of the application
* **/list/users**: List all users provided as configuration
* **/list/source/{name}**: Lists the configurations of the configuration source with the given name


== Expected Configurations
The following system properties are supported: +

* **allowedUsers**: The list of users with password in the form of **user:pwd{,user:pwd}**, which is required
* **listAllConfigAllowed**: True, if all configs are allowed to be loaded by clients, defaults to false

== Running with Hammock
When running this sample with Hammock, then configurations are expected to be provided via Java System Properties
during startup. +

To build this sample execute

* ``mvn clean install -Phammock``

To run the sample go to execute

* ``java -jar -DallowedUsers=<user_pwd_list> [-DlistAllConfigAllowed=<true|false>] target/config-1.0.0-SNAPSHOT-hammock.jar``
